fix bug for klp on x64
missing the processing for klp in build script

Signed-off-by: Lei Chen <lennychen@tencent.com>

diff --git a/kpatch-build/kpatch-build-tlinux b/kpatch-build/kpatch-build-tlinux
--- a/kpatch-build/kpatch-build-tlinux
+++ b/kpatch-build/kpatch-build-tlinux
@@ -573,10 +573,20 @@ KPATCH_MODULE=true
 
 # kernel option checking
 grep -q "CONFIG_DEBUG_INFO=y" "$CONFIGFILE" || die "kernel doesn't have 'CONFIG_DEBUG_INFO' enabled"
-
-# tlinux DOES NOT support for livepatch in the kernel. Kpatch core module is needed.
-find_core_symvers || die "unable to find Module.symvers for kpatch core module"
-KBUILD_EXTRA_SYMBOLS="$SYMVERSFILE"
+if grep -q "CONFIG_LIVEPATCH=y" "$CONFIGFILE"; then
+	# The kernel supports livepatch.
+	if version_gte "${KERN_TAG//-*/}" 4.7.0 || is_rhel "$KERN_TAG"; then
+		# Use new .klp.rela. sections
+		KPATCH_MODULE=false
+		if version_gte "${KERN_TAG//-*/}" 4.9.0 || is_rhel "$KERN_TAG"; then
+			KPATCH_LDFLAGS="--unique=.parainstructions --unique=.altinstructions"
+		fi
+	fi
+else
+	# No support for livepatch in the kernel. Kpatch core module is needed.
+	find_core_symvers || die "unable to find Module.symvers for kpatch core module"
+	KBUILD_EXTRA_SYMBOLS="$SYMVERSFILE"
+fi
 
 # optional kernel configs:
 if grep -q "CONFIG_PARAVIRT=y" "$CONFIGFILE"; then
@@ -652,7 +662,9 @@ fi
 for i in $(cat "$TEMPDIR/changed_objs")
 do
 	mkdir -p "$TEMPDIR/patched/$(dirname "$i")" || die
-	cp -f "$SRCDIR/$i" "$TEMPDIR/patched/$i" || die
+	if [[ -f "$SRCDIR/$i" ]]; then
+		cp -f "$SRCDIR/$i" "$TEMPDIR/patched/$i" || die
+	fi
 done
 
 echo "Extracting new and modified ELF sections"
@@ -723,7 +735,6 @@ for i in $FILES; do
 
 		# create-diff-object orig.o patched.o parent-name parent-symtab
 		#		     Module.symvers patch-mod-name output.o
-
 		"$TOOLSDIR"/create-diff-object "orig/$i" "patched/$i" "$KOBJFILE_NAME" \
 			"$SYMTAB" "$SYMVERS_FILE" "${MODNAME//-/_}" \
 			"output/$i" 2>&1 | logger 0
@@ -796,6 +807,15 @@ KPATCH_BUILD="$KPATCH_BUILD" KPATCH_NAME="$MODNAME" \
 KBUILD_EXTRA_SYMBOLS="$KBUILD_EXTRA_SYMBOLS" \
 KPATCH_LDFLAGS="$KPATCH_LDFLAGS" \
 	make 2>&1 | logger || die
+
+if ! "$KPATCH_MODULE"; then
+	if [[ -z "$KPATCH_LDFLAGS" ]]; then
+		extra_flags="--no-klp-arch-sections"
+	fi
+	cp "$TEMPDIR/patch/$MODNAME.ko" "$TEMPDIR/patch/tmp.ko" || die
+	"$TOOLSDIR"/create-klp-module $extra_flags "$TEMPDIR/patch/tmp.ko" "$TEMPDIR/patch/$MODNAME.ko" 2>&1 | logger 1
+	check_pipe_status create-klp-module
+fi
 
 readelf --wide --symbols "$TEMPDIR/patch/$MODNAME.ko" 2>/dev/null | \
 	awk '($4=="FUNC" || $4=="OBJECT") && ($5=="GLOBAL" || $5=="WEAK") && $7!="UND" {print $NF}' \
